<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Classification | Stats For You</title>
  <meta name="description" content="<p>This book provides an introduction to various topics in statistics and
probability.</p>" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Classification | Stats For You" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This book provides an introduction to various topics in statistics and
probability.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Classification | Stats For You" />
  
  <meta name="twitter:description" content="<p>This book provides an introduction to various topics in statistics and
probability.</p>" />
  

<meta name="author" content="Frederick De Baene" />


<meta name="date" content="2025-02-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="logistic-models-and-deviance.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Stats For You</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a></li>
<li class="chapter" data-level="2" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>2</b> Classification</a>
<ul>
<li class="chapter" data-level="2.1" data-path="classification.html"><a href="classification.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="classification.html"><a href="classification.html#bernoulli-random-variable"><i class="fa fa-check"></i><b>2.2</b> Bernoulli Random Variable</a></li>
<li class="chapter" data-level="2.3" data-path="classification.html"><a href="classification.html#conditional-probabilities"><i class="fa fa-check"></i><b>2.3</b> Conditional Probabilities</a></li>
<li class="chapter" data-level="2.4" data-path="classification.html"><a href="classification.html#logistic-regression-model"><i class="fa fa-check"></i><b>2.4</b> Logistic Regression Model</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html"><i class="fa fa-check"></i><b>3</b> Logistic Models and Deviance</a>
<ul>
<li class="chapter" data-level="3.1" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#models"><i class="fa fa-check"></i><b>3.1</b> Models</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#proposed-model"><i class="fa fa-check"></i><b>3.1.1</b> Proposed Model</a></li>
<li class="chapter" data-level="3.1.2" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#null-model"><i class="fa fa-check"></i><b>3.1.2</b> Null Model</a></li>
<li class="chapter" data-level="3.1.3" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#saturated-model"><i class="fa fa-check"></i><b>3.1.3</b> Saturated Model</a></li>
<li class="chapter" data-level="3.1.4" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#models-and-deviance"><i class="fa fa-check"></i><b>3.1.4</b> Models and Deviance</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#likelihood-and-log-likelihood"><i class="fa fa-check"></i><b>3.2</b> Likelihood and Log-Likelihood</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#proposed-model-1"><i class="fa fa-check"></i><b>3.2.1</b> Proposed Model</a></li>
<li class="chapter" data-level="3.2.2" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#null-model-1"><i class="fa fa-check"></i><b>3.2.2</b> Null Model</a></li>
<li class="chapter" data-level="3.2.3" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#saturated-model-1"><i class="fa fa-check"></i><b>3.2.3</b> Saturated Model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#deviance"><i class="fa fa-check"></i><b>3.3</b> Deviance</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stats For You</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="classification" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Classification<a href="classification.html#classification" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Classification problems occur in settings where the response <span class="math inline">\(Y\)</span> is qualitative
instead of quantitative. The set of possible values for the response <span class="math inline">\(Y\)</span> is
limited in size. Furthermore, if the response <span class="math inline">\(Y\)</span> can only take on one out of
two possible values, then the response <span class="math inline">\(Y\)</span> is binary.</p>
<div id="introduction" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Introduction<a href="classification.html#introduction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this chapter, we will use the <strong>Heart Failure Prediction</strong> data set.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="classification.html#cb1-1" tabindex="-1"></a>heart <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(</span>
<span id="cb1-2"><a href="classification.html#cb1-2" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">&quot;data/heart.xls&quot;</span>,</span>
<span id="cb1-3"><a href="classification.html#cb1-3" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb1-4"><a href="classification.html#cb1-4" tabindex="-1"></a>)</span></code></pre></div>
<p>This data set comprises <span class="math inline">\(n = 918\)</span> observations. In this data set,
the response <span class="math inline">\(HeartDisease\)</span> can be represented by an indicator variable <span class="math inline">\(HD\)</span>.
The variable <span class="math inline">\(HD = 1\)</span> if a patient has heart failure and <span class="math inline">\(HD = 0\)</span> if otherwise.</p>
<p>Note that the response variable does not take on a numerical value. There are
only two possible values: include <strong>YES</strong> (<span class="math inline">\(HD = 1\)</span>) and <strong>NO</strong> (<span class="math inline">\(HD = 0\)</span>).</p>
</div>
<div id="bernoulli-random-variable" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Bernoulli Random Variable<a href="classification.html#bernoulli-random-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Because there are only two possible outcomes for the response <span class="math inline">\(HD\)</span>, it is a a
Bernoulli random variable (binary random variable). The possible outcomes
include: success or failure (yes or no; 1 or 0). A Bernoulli random variable
follows a Bernoulli distribution (discrete probability distribution), which is
defined by a single parameter:</p>
<p><span class="math display">\[
HD \sim Bernoulli(\pi)
\]</span></p>
<p>with <span class="math inline">\(\pi\)</span> the probability of success in a single trial. We can use the data
to estimate <span class="math inline">\(\pi\)</span>, i.e., the probability that a patient has heart failure.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="classification.html#cb2-1" tabindex="-1"></a><span class="co"># Estimate the probability of a heart disease</span></span>
<span id="cb2-2"><a href="classification.html#cb2-2" tabindex="-1"></a>hd_prob <span class="ot">&lt;-</span> <span class="fu">mean</span>(heart[[<span class="st">&quot;HeartDisease&quot;</span>]])</span></code></pre></div>
<p>We obtain an estimate of <span class="math inline">\(\hat{\pi} = 0.55\)</span>. In other words,
<span class="math inline">\(P(Y = 1) = 0.55\)</span> is the probability of a patient in this
sample having heart failure. We can visualize this as follows:</p>
<p><img src="_main_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="conditional-probabilities" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Conditional Probabilities<a href="classification.html#conditional-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We estimated that the probability of a single patient having a heart disease
equals <span class="math inline">\(\hat{\pi} = 0.55\)</span>. This probability does not take into
account any additional patient information. We can, however, take into account
this additional information on the patient to determine the probability of a
heart disease. This probability is called a conditional probability.</p>
<p>For example, we can take into account the sex of a patient to determine the
patient’s probability of a heart disease:</p>
<p><span class="math display">\[
P(HD = 1 | SEX)
\]</span></p>
<p>Again, we can use the data to estimate these conditional probabilities:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="classification.html#cb3-1" tabindex="-1"></a><span class="co"># Estimate conditional probabilities (conditioning on sex)</span></span>
<span id="cb3-2"><a href="classification.html#cb3-2" tabindex="-1"></a>hd_prob_m <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">subset</span>(<span class="at">x =</span> heart<span class="sc">$</span>HeartDisease, <span class="at">subset =</span> heart<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">&quot;M&quot;</span>))</span>
<span id="cb3-3"><a href="classification.html#cb3-3" tabindex="-1"></a>hd_prob_f <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">subset</span>(<span class="at">x =</span> heart<span class="sc">$</span>HeartDisease, <span class="at">subset =</span> heart<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">&quot;F&quot;</span>))</span></code></pre></div>
<p>We see that the probability of heart disease for male patients is
<span class="math inline">\(P(HD = 1 | SEX = M) = 0.63\)</span>, while for female patients it
is <span class="math inline">\(P(HD = 1 | SEX = F) = 0.26\)</span>. It seems that male patients
have a higher probability of having a heart disease compared to female patients.</p>
<p>Conditional probabilities allows us to take into account additional information
to more accurately estimate the probability of a certain event (i.e., heart
disease) occurring. The concept of conditional probabilities is important to
understand how classifiers, such as logistic regression models, work.</p>
</div>
<div id="logistic-regression-model" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Logistic Regression Model<a href="classification.html#logistic-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this chapter, we will explore how conditional probabilities fit into a
logistic regression model. Logistic regression models are nonlinear regression
models and fit into the framework of generalized linear models. A logistic
regression model can be used to estimate the probability of a certain event
occurring taking into account additional information. In our case, a logistic
regression model can be fitted to the hart disease data set to estimate the
probability of a heart disease given the patient’s sex.</p>
<p>First, we fit a logistic model. In this first example, the logistic model
includes a single categorical predictor. Therefore, we must first ensure that
the data set contains this predictor as a factor variable.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="classification.html#cb4-1" tabindex="-1"></a><span class="co"># Create a new variable in the heart data set. This new variable is a factor </span></span>
<span id="cb4-2"><a href="classification.html#cb4-2" tabindex="-1"></a><span class="co"># that represents the sex of a patient.</span></span>
<span id="cb4-3"><a href="classification.html#cb4-3" tabindex="-1"></a>heart<span class="sc">$</span>FSex <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart<span class="sc">$</span>Sex)</span></code></pre></div>
<p>We must also be aware of the coding scheme used for this categorical predictor.
We can use a call to <code>contrasts()</code> to verify the coding scheme.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="classification.html#cb5-1" tabindex="-1"></a><span class="fu">contrasts</span>(heart<span class="sc">$</span>FSex)</span></code></pre></div>
<pre><code>##   M
## F 0
## M 1</code></pre>
<p>We see that a dummy/treatment coding scheme is used. The reference level is <code>F</code>,
i.e., female patients form the reference group. We can now fit the logistic
regression model.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="classification.html#cb7-1" tabindex="-1"></a><span class="co"># Fit a logistic regression model with a single factor (sex)</span></span>
<span id="cb7-2"><a href="classification.html#cb7-2" tabindex="-1"></a>fit_lrm <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb7-3"><a href="classification.html#cb7-3" tabindex="-1"></a>  <span class="at">formula =</span> HeartDisease <span class="sc">~</span> FSex,</span>
<span id="cb7-4"><a href="classification.html#cb7-4" tabindex="-1"></a>  <span class="at">data =</span> heart,</span>
<span id="cb7-5"><a href="classification.html#cb7-5" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>)</span>
<span id="cb7-6"><a href="classification.html#cb7-6" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = HeartDisease ~ FSex, family = binomial(link = &quot;logit&quot;), 
##     data = heart)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.0508     0.1643  -6.396  1.6e-10 ***
## FSexM         1.5904     0.1814   8.766  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1262.1  on 917  degrees of freedom
## Residual deviance: 1175.0  on 916  degrees of freedom
## AIC: 1179
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The fitted model is the following:</p>
<p><span class="math display">\[
logit(\pi_i) = -1.0508 + 1.5904 \times X_{i\_male}
\]</span></p>
<p>with <span class="math inline">\(\hat{\beta_0} = -1.05\)</span>,
<span class="math inline">\(\hat{\beta_1} = 1.59\)</span>, and <span class="math inline">\(X_{i\_male}\)</span> an
indicator variable with <span class="math inline">\(X_{i\_male} = 1\)</span> if the patient is male and 0 otherwise.</p>
<p>In the following sections of this chapter, we will break down how to obtain the
coefficient estimates and what they mean. We will also explain how we can use
this fitted model to obtain the same conditional probabilities from the
previous sections.</p>
<p>For an in-depth explanation what the values related to the deviance mean and
how we can use these to assess how well the model fits the data, cfr. the
appropriate section.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-models-and-deviance.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-classification.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
