<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Logistic Models and Deviance | Stats For You</title>
  <meta name="description" content="<p>This book provides an introduction to various topics in statistics and
probability.</p>" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Logistic Models and Deviance | Stats For You" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This book provides an introduction to various topics in statistics and
probability.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Logistic Models and Deviance | Stats For You" />
  
  <meta name="twitter:description" content="<p>This book provides an introduction to various topics in statistics and
probability.</p>" />
  

<meta name="author" content="Frederick De Baene" />


<meta name="date" content="2025-10-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="missingness.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Stats For You</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a></li>
<li class="chapter" data-level="2" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html"><i class="fa fa-check"></i><b>2</b> Logistic Models and Deviance</a>
<ul>
<li class="chapter" data-level="2.1" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#models"><i class="fa fa-check"></i><b>2.1</b> Models</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#proposed-model"><i class="fa fa-check"></i><b>2.1.1</b> Proposed Model</a></li>
<li class="chapter" data-level="2.1.2" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#null-model"><i class="fa fa-check"></i><b>2.1.2</b> Null Model</a></li>
<li class="chapter" data-level="2.1.3" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#saturated-model"><i class="fa fa-check"></i><b>2.1.3</b> Saturated Model</a></li>
<li class="chapter" data-level="2.1.4" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#models-and-deviance"><i class="fa fa-check"></i><b>2.1.4</b> Models and Deviance</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#likelihood-and-log-likelihood"><i class="fa fa-check"></i><b>2.2</b> Likelihood and Log-Likelihood</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#proposed-model-1"><i class="fa fa-check"></i><b>2.2.1</b> Proposed Model</a></li>
<li class="chapter" data-level="2.2.2" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#null-model-1"><i class="fa fa-check"></i><b>2.2.2</b> Null Model</a></li>
<li class="chapter" data-level="2.2.3" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#saturated-model-1"><i class="fa fa-check"></i><b>2.2.3</b> Saturated Model</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="logistic-models-and-deviance.html"><a href="logistic-models-and-deviance.html#deviance"><i class="fa fa-check"></i><b>2.3</b> Deviance</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="missingness.html"><a href="missingness.html"><i class="fa fa-check"></i><b>3</b> Missingness</a>
<ul>
<li class="chapter" data-level="3.1" data-path="missingness.html"><a href="missingness.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="missingness.html"><a href="missingness.html#missingess-patterns"><i class="fa fa-check"></i><b>3.2</b> Missingess Patterns</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="missingness.html"><a href="missingness.html#simulation-setup"><i class="fa fa-check"></i><b>3.2.1</b> Simulation Setup</a></li>
<li class="chapter" data-level="3.2.2" data-path="missingness.html"><a href="missingness.html#missingness-completely-at-random"><i class="fa fa-check"></i><b>3.2.2</b> Missingness Completely at Random</a></li>
<li class="chapter" data-level="3.2.3" data-path="missingness.html"><a href="missingness.html#missingness-at-random"><i class="fa fa-check"></i><b>3.2.3</b> Missingness at Random</a></li>
<li class="chapter" data-level="3.2.4" data-path="missingness.html"><a href="missingness.html#missingness-not-at-random"><i class="fa fa-check"></i><b>3.2.4</b> Missingness Not at Random</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="distributions-and-measures.html"><a href="distributions-and-measures.html"><i class="fa fa-check"></i><b>4</b> Distributions and Measures</a>
<ul>
<li class="chapter" data-level="4.1" data-path="distributions-and-measures.html"><a href="distributions-and-measures.html#distributions"><i class="fa fa-check"></i><b>4.1</b> Distributions</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stats For You</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-models-and-deviance" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">2</span> Logistic Models and Deviance<a href="logistic-models-and-deviance.html#logistic-models-and-deviance" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>When fitting a logistic regression model to a data set, R outputs several key
metrics, including the <strong>null deviance</strong> and the <strong>residual deviance</strong>, along
with their respective degrees of freedom. This chapter aims to clarify the
calculation methods and meaning of these deviance values. We will use the first
20 observations from a heart disease data set, fit a logistic regression model
to this data, and manually compute the deviance values to illustrate how they
are actually calculated.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="logistic-models-and-deviance.html#cb1-1" tabindex="-1"></a><span class="co"># Read the data and only retain the first 20 observations</span></span>
<span id="cb1-2"><a href="logistic-models-and-deviance.html#cb1-2" tabindex="-1"></a>heart <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;data/heart.xls&quot;</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-3"><a href="logistic-models-and-deviance.html#cb1-3" tabindex="-1"></a>heart <span class="ot">&lt;-</span> <span class="fu">head</span>(heart, <span class="dv">20</span>)</span></code></pre></div>
<div id="models" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Models<a href="logistic-models-and-deviance.html#models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To understand what these deviance values are, we must first understand the
following three models:</p>
<ul>
<li>the <strong>null</strong> model (<span class="math inline">\(M_0\)</span>),</li>
<li>the <strong>proposed</strong> model (<span class="math inline">\(M_p\)</span>),</li>
<li>and the <strong>saturated</strong> model (<span class="math inline">\(M_s\)</span>).</li>
</ul>
<p>These three models are used to calculate the two deviance values outputted by R,
i.e., the null deviance (the deviance of <span class="math inline">\(M_0\)</span>) and the residual deviance(the
deviance of <span class="math inline">\(M_p\)</span>).</p>
<div id="proposed-model" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Proposed Model<a href="logistic-models-and-deviance.html#proposed-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The proposed model <span class="math inline">\(M_p\)</span> is the model of interest. In our example, it is used to
estimate the probability of heart disease for each patient, conditioning on that
patient’s age. The model is represented as follows:</p>
<p><span class="math display">\[
logit(\pi_i) = \beta_0 + \beta_1 \times Age_i + \epsilon_i
\]</span></p>
<p>with <span class="math inline">\(\pi_i = P(HD_i = 1 | Age_i)\)</span> the conditional probability of a heart
disease for patient <span class="math inline">\(i\)</span>, <span class="math inline">\(Age_i\)</span> the age of patient <span class="math inline">\(i\)</span>, and <span class="math inline">\(\epsilon_i\)</span> the
random error of the model for the <span class="math inline">\(i\)</span>’th observation. We can fit the proposed
model as follows:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="logistic-models-and-deviance.html#cb2-1" tabindex="-1"></a>fit_p <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb2-2"><a href="logistic-models-and-deviance.html#cb2-2" tabindex="-1"></a>  <span class="at">formula =</span> HeartDisease <span class="sc">~</span> Age,</span>
<span id="cb2-3"><a href="logistic-models-and-deviance.html#cb2-3" tabindex="-1"></a>  <span class="at">data =</span> heart,</span>
<span id="cb2-4"><a href="logistic-models-and-deviance.html#cb2-4" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>)</span>
<span id="cb2-5"><a href="logistic-models-and-deviance.html#cb2-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = HeartDisease ~ Age, family = binomial(link = &quot;logit&quot;), 
##     data = heart)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -2.48884    2.87127  -0.867    0.386
## Age          0.04571    0.06191   0.738    0.460
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 26.920  on 19  degrees of freedom
## Residual deviance: 26.365  on 18  degrees of freedom
## AIC: 30.365
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>We obtain the null deviance <span class="math inline">\(D_0 = 26.9\)</span> and the
residual deviance <span class="math inline">\(D_p = 26.4\)</span>.</p>
</div>
<div id="null-model" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Null Model<a href="logistic-models-and-deviance.html#null-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The null model <span class="math inline">\(M_0\)</span> is a model without any predictors. It only contains an
intercept <span class="math inline">\(\beta_0\)</span>:</p>
<p><span class="math display">\[
logit(\pi_i) = \beta_0 + \epsilon_i
\]</span></p>
<p>The estimated probability of heart disease is the same for each patient. The
null model <span class="math inline">\(M_0\)</span> is fitted as follows:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="logistic-models-and-deviance.html#cb4-1" tabindex="-1"></a>fit_0 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb4-2"><a href="logistic-models-and-deviance.html#cb4-2" tabindex="-1"></a>  <span class="at">formula =</span> HeartDisease <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb4-3"><a href="logistic-models-and-deviance.html#cb4-3" tabindex="-1"></a>  <span class="at">data =</span> heart,</span>
<span id="cb4-4"><a href="logistic-models-and-deviance.html#cb4-4" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>)</span>
<span id="cb4-5"><a href="logistic-models-and-deviance.html#cb4-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = HeartDisease ~ 1, family = binomial(link = &quot;logit&quot;), 
##     data = heart)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  -0.4055     0.4564  -0.888    0.374
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 26.92  on 19  degrees of freedom
## Residual deviance: 26.92  on 19  degrees of freedom
## AIC: 28.92
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>R outputs the null deviance <span class="math inline">\(D_0\)</span> and the residual deviance <span class="math inline">\(D_p\)</span>, which both
equal 26.9. They are the same because <span class="math inline">\(M_p\)</span> is the
same as <span class="math inline">\(M_0\)</span> (neither of them contains a predictor, only an intercept).</p>
</div>
<div id="saturated-model" class="section level3 hasAnchor" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Saturated Model<a href="logistic-models-and-deviance.html#saturated-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The saturated model <span class="math inline">\(M_s\)</span> is a model that perfectly fits data. This model
perfectly predicts the outcome for each patient in the data set. If patient <span class="math inline">\(i\)</span>
has a heart disease (<span class="math inline">\(HD_i = 1\)</span>), then <span class="math inline">\(\hat{\pi_i} = 1\)</span>. If patient <span class="math inline">\(i\)</span> does
not have a heart disease (<span class="math inline">\(HD_i = 0\)</span>), then <span class="math inline">\(\hat{\pi_i} = 0\)</span>. We will not fit a
saturated model <span class="math inline">\(M_s\)</span> as such to the data, but continue our explanation knowing
the fact that the model perfectly predicts the outcome for each observation <span class="math inline">\(i\)</span>.</p>
</div>
<div id="models-and-deviance" class="section level3 hasAnchor" number="2.1.4">
<h3><span class="header-section-number">2.1.4</span> Models and Deviance<a href="logistic-models-and-deviance.html#models-and-deviance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Since the saturated model <span class="math inline">\(M_s\)</span> perfectly fits the data, it serves as our
reference point for assessing goodness-of-fit. The proposed model <span class="math inline">\(M_p\)</span> and the
null model <span class="math inline">\(M_0\)</span> are compared to the saturated model in terms of their
goodness-of-fit. The result of these comparisons is a deviance value for each
model. The deviance quantifies the degree to which the null model and the
proposed model deviate from the saturated model in terms of goodness-of-fit. To
calculate the actual deviance, we utilize the likelihoods and log-likelihoods of
the models (see below for further details).</p>
</div>
</div>
<div id="likelihood-and-log-likelihood" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Likelihood and Log-Likelihood<a href="logistic-models-and-deviance.html#likelihood-and-log-likelihood" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The likelihood is a probability that indicates how likely it is that the
parameters take on particular values <strong>given a particular sample</strong>. As the
sample is given, the values for the outcome and predictor are not variables. The
parameter values are the variables. We can represent the likelihood function as
follows:</p>
<p><span class="math display">\[
L(\theta | (x_1, y_1), (x_2, y_2), ..., (x_n, y_n))
= \prod_{i = 1}^{n} f_Y(y_i; x_i, \theta)
\]</span></p>
<p>with <span class="math inline">\(\theta\)</span> the parameters of interest, <span class="math inline">\(n\)</span> the sample size, and
<span class="math inline">\(f_Y(y; x, \theta)\)</span> the probability mass function for the response. Calculating
the likelihood involves taking the product of many probabilities (i.e., values
between 0 and 1), and therefore results in a very small value. For computational
reasons, often the log-likelihood is calculated instead of the likelihood.</p>
<p><span class="math display">\[
\begin{aligned}
l(\theta | (x_1, y_1), (x_2, y_2), ..., (x_n, y_n))
&amp;= log[\prod_{i = 1}^{n} f_Y(y_i; x_i, \theta)] \\
&amp;= \sum_{i = 1}^{n} log(f_Y(y_i; x_i, \theta))
\end{aligned}
\]</span></p>
<div id="proposed-model-1" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Proposed Model<a href="logistic-models-and-deviance.html#proposed-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We start by calculating the likelihood and log-likelihood of <span class="math inline">\(M_p\)</span>.</p>
<p><span class="math display">\[
L(\theta | (x_1, y_1), (x_2, y_2), ..., (x_n, y_n)) = \prod_{i = 1}^{n} f_Y(y_i; x_i, \theta)
\]</span></p>
<p>with <span class="math inline">\(\theta\)</span> representing the parameters that are the variables and <span class="math inline">\(n\)</span> the
sample size. To define the likelihood function, we must first determine the
probability mass function for the response. The PMF
defines the probability distribution of a discrete random variable. Remember
that a logistic regression model is used to predict the outcome for a discrete
random variable, and more specifically a binary random variable that follows a
Bernoulli distribution:</p>
<p><span class="math display">\[
HD \sim Bernoulli(\pi)
\]</span></p>
<p>The probability mass function (PMF) of a Bernoulli distribution is the
following:</p>
<p><span class="math display">\[
f_Y(y; \pi) = \pi^{y} \times (1 - \pi)^{1 - y}
\]</span></p>
<p>Therefore, we use the PMF of the Bernoulli distribution for the likelihood
function:</p>
<p><span class="math display">\[
L(\theta | (x_1, y_1), (x_2, y_2), ..., (x_n, y_n))
= \prod_{i = 1}^{n} \pi_{i}^{y_i} \times (1 - \pi_i)^{1 - y_i}
\]</span></p>
<p>with <span class="math inline">\(\theta\)</span> representing the regression coefficients of the logistic
regression model. We can now also define the log-likelihood function:</p>
<p><span class="math display">\[
\begin{aligned}
l(\theta | (x_1, y_1), (x_2, y_2), ..., (x_n, y_n))
&amp;= log[\prod_{i = 1}^{n} \pi_{i}^{y_i} \times (1 - \pi_i)^{1 - y_i}] \\
&amp;= \sum_{i = 1}^{n} [y_i \times log(\pi_i) + (1 - y_i) \times log(1 - \pi_i)]
\end{aligned}
\]</span></p>
<p>Using our fitted model <span class="math inline">\(M_p\)</span>, how can we now obtain the log-likelihood? We start
by obtaining the estimated probability of observing the actual outcome for each
observation in the data set. We focus on the third observation in the data set.
We see that <span class="math inline">\(Age_3 = 37\)</span> and <span class="math inline">\(HD_3 = 0\)</span>. We can use our model to obtain the
probability of a heart disease:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="logistic-models-and-deviance.html#cb6-1" tabindex="-1"></a><span class="co"># Estimate the probability of a heart disease for i = 3</span></span>
<span id="cb6-2"><a href="logistic-models-and-deviance.html#cb6-2" tabindex="-1"></a>hd_prob_003 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_p, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)[<span class="dv">3</span>]</span>
<span id="cb6-3"><a href="logistic-models-and-deviance.html#cb6-3" tabindex="-1"></a>hd_prob_003</span></code></pre></div>
<pre><code>##         3 
## 0.3105577</code></pre>
<p>We see that this probability is
<span class="math inline">\(P(HD_3 = 1 | Age_i = 37) = \pi_i = 0.31\)</span>. Assume that
our sample only comprises this one patient, then the likelihood would be:</p>
<p><span class="math display">\[
\begin{aligned}
L(\theta | (Age_i, HD_i))
&amp;= \prod_{i = 1}^{n} f_Y(y_i; x_i, \theta) \\
&amp;= \prod_{i = 1}^{n} \pi_{i}^{y_i} \times (1 - \pi_i)^{1 - y_i} \\
&amp;= 0.3105577^{0} \times (1 - 0.3105577)^{1 - 0} \\
&amp;= 1 \times 0.6894423^{1} \\
&amp;= 0.6894423
\end{aligned}
\]</span></p>
<p>So, to calculate the likelihood, first, we calculate the estimated probability
with which the actual outcome occurs.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="logistic-models-and-deviance.html#cb8-1" tabindex="-1"></a><span class="co"># Create a copy of the data frame as to not overwrite the original data</span></span>
<span id="cb8-2"><a href="logistic-models-and-deviance.html#cb8-2" tabindex="-1"></a>heart_p <span class="ot">&lt;-</span> heart</span>
<span id="cb8-3"><a href="logistic-models-and-deviance.html#cb8-3" tabindex="-1"></a></span>
<span id="cb8-4"><a href="logistic-models-and-deviance.html#cb8-4" tabindex="-1"></a><span class="co"># Calculate the probability of a patient having or not having a heart disease </span></span>
<span id="cb8-5"><a href="logistic-models-and-deviance.html#cb8-5" tabindex="-1"></a><span class="co"># using the proposed model (i.e., given the patient&#39;s age)</span></span>
<span id="cb8-6"><a href="logistic-models-and-deviance.html#cb8-6" tabindex="-1"></a>heart_p<span class="sc">$</span>EstProb_HD_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_p, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb8-7"><a href="logistic-models-and-deviance.html#cb8-7" tabindex="-1"></a>heart_p<span class="sc">$</span>EstProb_HD_0 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">predict</span>(fit_p, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb8-8"><a href="logistic-models-and-deviance.html#cb8-8" tabindex="-1"></a></span>
<span id="cb8-9"><a href="logistic-models-and-deviance.html#cb8-9" tabindex="-1"></a>heart_p <span class="ot">&lt;-</span> heart_p <span class="sc">%&gt;%</span></span>
<span id="cb8-10"><a href="logistic-models-and-deviance.html#cb8-10" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb8-11"><a href="logistic-models-and-deviance.html#cb8-11" tabindex="-1"></a>    <span class="at">ProbOutcome =</span> EstProb_HD_1<span class="sc">^</span>HeartDisease <span class="sc">*</span> EstProb_HD_0<span class="sc">^</span>(<span class="dv">1</span> <span class="sc">-</span> HeartDisease),</span>
<span id="cb8-12"><a href="logistic-models-and-deviance.html#cb8-12" tabindex="-1"></a>    <span class="at">LogProbOutcome =</span> <span class="fu">log</span>(ProbOutcome)</span>
<span id="cb8-13"><a href="logistic-models-and-deviance.html#cb8-13" tabindex="-1"></a>  )</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Age</th>
<th align="right">Heart Disease</th>
<th align="right">P(HD = 1)</th>
<th align="right">P(HD = 0)</th>
<th align="right">P(Outcome)</th>
<th align="right">Log(P(Outcome))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">40</td>
<td align="right">0</td>
<td align="right">0.3406546</td>
<td align="right">0.6593454</td>
<td align="right">0.6593454</td>
<td align="right">-0.4165078</td>
</tr>
<tr class="even">
<td align="right">49</td>
<td align="right">1</td>
<td align="right">0.4380759</td>
<td align="right">0.5619241</td>
<td align="right">0.4380759</td>
<td align="right">-0.8253630</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">0</td>
<td align="right">0.3105577</td>
<td align="right">0.6894423</td>
<td align="right">0.6894423</td>
<td align="right">-0.3718723</td>
</tr>
<tr class="even">
<td align="right">48</td>
<td align="right">1</td>
<td align="right">0.4268570</td>
<td align="right">0.5731430</td>
<td align="right">0.4268570</td>
<td align="right">-0.8513061</td>
</tr>
<tr class="odd">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0.4948960</td>
<td align="right">0.5051040</td>
<td align="right">0.5051040</td>
<td align="right">-0.6829909</td>
</tr>
<tr class="even">
<td align="right">39</td>
<td align="right">0</td>
<td align="right">0.3304634</td>
<td align="right">0.6695366</td>
<td align="right">0.6695366</td>
<td align="right">-0.4011694</td>
</tr>
<tr class="odd">
<td align="right">45</td>
<td align="right">0</td>
<td align="right">0.3936917</td>
<td align="right">0.6063083</td>
<td align="right">0.6063083</td>
<td align="right">-0.5003666</td>
</tr>
<tr class="even">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0.4948960</td>
<td align="right">0.5051040</td>
<td align="right">0.5051040</td>
<td align="right">-0.6829909</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">1</td>
<td align="right">0.3105577</td>
<td align="right">0.6894423</td>
<td align="right">0.3105577</td>
<td align="right">-1.1693854</td>
</tr>
<tr class="even">
<td align="right">48</td>
<td align="right">0</td>
<td align="right">0.4268570</td>
<td align="right">0.5731430</td>
<td align="right">0.5731430</td>
<td align="right">-0.5566201</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">0</td>
<td align="right">0.3105577</td>
<td align="right">0.6894423</td>
<td align="right">0.6894423</td>
<td align="right">-0.3718723</td>
</tr>
<tr class="even">
<td align="right">58</td>
<td align="right">1</td>
<td align="right">0.5405183</td>
<td align="right">0.4594817</td>
<td align="right">0.5405183</td>
<td align="right">-0.6152267</td>
</tr>
<tr class="odd">
<td align="right">39</td>
<td align="right">0</td>
<td align="right">0.3304634</td>
<td align="right">0.6695366</td>
<td align="right">0.6695366</td>
<td align="right">-0.4011694</td>
</tr>
<tr class="even">
<td align="right">49</td>
<td align="right">1</td>
<td align="right">0.4380759</td>
<td align="right">0.5619241</td>
<td align="right">0.4380759</td>
<td align="right">-0.8253630</td>
</tr>
<tr class="odd">
<td align="right">42</td>
<td align="right">0</td>
<td align="right">0.3614779</td>
<td align="right">0.6385221</td>
<td align="right">0.6385221</td>
<td align="right">-0.4485990</td>
</tr>
<tr class="even">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0.4948960</td>
<td align="right">0.5051040</td>
<td align="right">0.5051040</td>
<td align="right">-0.6829909</td>
</tr>
<tr class="odd">
<td align="right">38</td>
<td align="right">1</td>
<td align="right">0.3204289</td>
<td align="right">0.6795711</td>
<td align="right">0.3204289</td>
<td align="right">-1.1380949</td>
</tr>
<tr class="even">
<td align="right">43</td>
<td align="right">0</td>
<td align="right">0.3720940</td>
<td align="right">0.6279060</td>
<td align="right">0.6279060</td>
<td align="right">-0.4653649</td>
</tr>
<tr class="odd">
<td align="right">60</td>
<td align="right">1</td>
<td align="right">0.5631245</td>
<td align="right">0.4368755</td>
<td align="right">0.5631245</td>
<td align="right">-0.5742545</td>
</tr>
<tr class="even">
<td align="right">36</td>
<td align="right">1</td>
<td align="right">0.3008561</td>
<td align="right">0.6991439</td>
<td align="right">0.3008561</td>
<td align="right">-1.2011233</td>
</tr>
</tbody>
</table>
<p>The above data show, given the fitted model, the probability with which each
actual outcome occurs, given the patient’s age, and also the log-transformed
probability. To obtain the log-likelihood of the fitted model <span class="math inline">\(LL_p\)</span>, we can now
just sum these log-transformed probabilities:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="logistic-models-and-deviance.html#cb9-1" tabindex="-1"></a><span class="co"># Obtain the log-likelihood for the proposed model</span></span>
<span id="cb9-2"><a href="logistic-models-and-deviance.html#cb9-2" tabindex="-1"></a>ll_p <span class="ot">&lt;-</span> <span class="fu">sum</span>(heart_p<span class="sc">$</span>LogProbOutcome)</span>
<span id="cb9-3"><a href="logistic-models-and-deviance.html#cb9-3" tabindex="-1"></a>ll_p</span></code></pre></div>
<pre><code>## [1] -13.18263</code></pre>
</div>
<div id="null-model-1" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Null Model<a href="logistic-models-and-deviance.html#null-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can also do this for the null model. Remember that the fitted probability
of a heart disease will be the same for each patient, as we do not take into
account any patient information. We can then compute the log-likelihood of the
null model as follows:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="logistic-models-and-deviance.html#cb11-1" tabindex="-1"></a><span class="co"># Create a copy of the data frame as to not overwrite the original data</span></span>
<span id="cb11-2"><a href="logistic-models-and-deviance.html#cb11-2" tabindex="-1"></a>heart_0 <span class="ot">&lt;-</span> heart</span>
<span id="cb11-3"><a href="logistic-models-and-deviance.html#cb11-3" tabindex="-1"></a></span>
<span id="cb11-4"><a href="logistic-models-and-deviance.html#cb11-4" tabindex="-1"></a><span class="co"># Calculate the probability of a patient having or not having a heart disease </span></span>
<span id="cb11-5"><a href="logistic-models-and-deviance.html#cb11-5" tabindex="-1"></a><span class="co"># using the null model (i.e., not taking into account any patient information)</span></span>
<span id="cb11-6"><a href="logistic-models-and-deviance.html#cb11-6" tabindex="-1"></a>heart_0<span class="sc">$</span>EstProb_HD_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_0, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb11-7"><a href="logistic-models-and-deviance.html#cb11-7" tabindex="-1"></a>heart_0<span class="sc">$</span>EstProb_HD_0 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">predict</span>(fit_0, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb11-8"><a href="logistic-models-and-deviance.html#cb11-8" tabindex="-1"></a></span>
<span id="cb11-9"><a href="logistic-models-and-deviance.html#cb11-9" tabindex="-1"></a>heart_0 <span class="ot">&lt;-</span> heart_0 <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="logistic-models-and-deviance.html#cb11-10" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb11-11"><a href="logistic-models-and-deviance.html#cb11-11" tabindex="-1"></a>    <span class="at">ProbOutcome =</span> EstProb_HD_1<span class="sc">^</span>HeartDisease <span class="sc">*</span> EstProb_HD_0<span class="sc">^</span>(<span class="dv">1</span> <span class="sc">-</span> HeartDisease),</span>
<span id="cb11-12"><a href="logistic-models-and-deviance.html#cb11-12" tabindex="-1"></a>    <span class="at">LogProbOutcome =</span> <span class="fu">log</span>(ProbOutcome)</span>
<span id="cb11-13"><a href="logistic-models-and-deviance.html#cb11-13" tabindex="-1"></a>  )</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Age</th>
<th align="right">Heart Disease</th>
<th align="right">P(HD = 1)</th>
<th align="right">P(HD = 0)</th>
<th align="right">P(Outcome)</th>
<th align="right">Log(P(Outcome))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">40</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="even">
<td align="right">49</td>
<td align="right">1</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.4</td>
<td align="right">-0.9162907</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="even">
<td align="right">48</td>
<td align="right">1</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.4</td>
<td align="right">-0.9162907</td>
</tr>
<tr class="odd">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="even">
<td align="right">39</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="odd">
<td align="right">45</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="even">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">1</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.4</td>
<td align="right">-0.9162907</td>
</tr>
<tr class="even">
<td align="right">48</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="even">
<td align="right">58</td>
<td align="right">1</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.4</td>
<td align="right">-0.9162907</td>
</tr>
<tr class="odd">
<td align="right">39</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="even">
<td align="right">49</td>
<td align="right">1</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.4</td>
<td align="right">-0.9162907</td>
</tr>
<tr class="odd">
<td align="right">42</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="even">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="odd">
<td align="right">38</td>
<td align="right">1</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.4</td>
<td align="right">-0.9162907</td>
</tr>
<tr class="even">
<td align="right">43</td>
<td align="right">0</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.6</td>
<td align="right">-0.5108256</td>
</tr>
<tr class="odd">
<td align="right">60</td>
<td align="right">1</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.4</td>
<td align="right">-0.9162907</td>
</tr>
<tr class="even">
<td align="right">36</td>
<td align="right">1</td>
<td align="right">0.4</td>
<td align="right">0.6</td>
<td align="right">0.4</td>
<td align="right">-0.9162907</td>
</tr>
</tbody>
</table>
<p>We obtain the log-likelihood of the null model <span class="math inline">\(LL_0\)</span> as follows:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="logistic-models-and-deviance.html#cb12-1" tabindex="-1"></a>ll_0 <span class="ot">&lt;-</span> <span class="fu">sum</span>(heart_0<span class="sc">$</span>LogProbOutcome)</span>
<span id="cb12-2"><a href="logistic-models-and-deviance.html#cb12-2" tabindex="-1"></a>ll_0</span></code></pre></div>
<pre><code>## [1] -13.46023</code></pre>
</div>
<div id="saturated-model-1" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Saturated Model<a href="logistic-models-and-deviance.html#saturated-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can follow the same procedure for <span class="math inline">\(M_s\)</span>. The saturated model perfectly fits
the data, so the estimated probability of heart disease reflects the actual
outcome. In other words, if <span class="math inline">\(HD_i = 1\)</span>, then <span class="math inline">\(P(HD_i = 1) = 1\)</span>. And if
<span class="math inline">\(HD_i = 0\)</span>, then <span class="math inline">\(P(HD_i = 1) = 0\)</span>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="logistic-models-and-deviance.html#cb14-1" tabindex="-1"></a><span class="co"># Create a copy of the data frame as to not overwrite the original data</span></span>
<span id="cb14-2"><a href="logistic-models-and-deviance.html#cb14-2" tabindex="-1"></a>heart_s <span class="ot">&lt;-</span> heart</span>
<span id="cb14-3"><a href="logistic-models-and-deviance.html#cb14-3" tabindex="-1"></a></span>
<span id="cb14-4"><a href="logistic-models-and-deviance.html#cb14-4" tabindex="-1"></a><span class="co"># Calculate the probability of a patient having or not having a heart disease </span></span>
<span id="cb14-5"><a href="logistic-models-and-deviance.html#cb14-5" tabindex="-1"></a><span class="co"># using the saturated model (i.e., the model perfectly fits the data)</span></span>
<span id="cb14-6"><a href="logistic-models-and-deviance.html#cb14-6" tabindex="-1"></a>heart_s<span class="sc">$</span>EstProb_HD_1 <span class="ot">&lt;-</span> heart_s<span class="sc">$</span>HeartDisease</span>
<span id="cb14-7"><a href="logistic-models-and-deviance.html#cb14-7" tabindex="-1"></a>heart_s<span class="sc">$</span>EstProb_HD_0 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> heart_s<span class="sc">$</span>HeartDisease</span>
<span id="cb14-8"><a href="logistic-models-and-deviance.html#cb14-8" tabindex="-1"></a></span>
<span id="cb14-9"><a href="logistic-models-and-deviance.html#cb14-9" tabindex="-1"></a>heart_s <span class="ot">&lt;-</span> heart_s <span class="sc">%&gt;%</span></span>
<span id="cb14-10"><a href="logistic-models-and-deviance.html#cb14-10" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb14-11"><a href="logistic-models-and-deviance.html#cb14-11" tabindex="-1"></a>    <span class="at">ProbOutcome =</span> EstProb_HD_1<span class="sc">^</span>HeartDisease <span class="sc">*</span> EstProb_HD_0<span class="sc">^</span>(<span class="dv">1</span> <span class="sc">-</span> HeartDisease),</span>
<span id="cb14-12"><a href="logistic-models-and-deviance.html#cb14-12" tabindex="-1"></a>    <span class="at">LogProbOutcome =</span> <span class="fu">log</span>(ProbOutcome)</span>
<span id="cb14-13"><a href="logistic-models-and-deviance.html#cb14-13" tabindex="-1"></a>  )</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Age</th>
<th align="right">Heart Disease</th>
<th align="right">P(HD = 1)</th>
<th align="right">P(HD = 0)</th>
<th align="right">P(Outcome)</th>
<th align="right">Log(P(Outcome))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">40</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">49</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">48</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">39</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">45</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">48</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">37</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">58</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">39</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">49</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">42</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">54</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">38</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">43</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">60</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">36</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>Finally, we obtain the log-likelihood for the saturated model <span class="math inline">\(LL_s\)</span>:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="logistic-models-and-deviance.html#cb15-1" tabindex="-1"></a>ll_s <span class="ot">&lt;-</span> <span class="fu">sum</span>(heart_s<span class="sc">$</span>LogProbOutcome)</span>
<span id="cb15-2"><a href="logistic-models-and-deviance.html#cb15-2" tabindex="-1"></a>ll_s</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
</div>
</div>
<div id="deviance" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Deviance<a href="logistic-models-and-deviance.html#deviance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As stated earlier, the saturated model <span class="math inline">\(M_s\)</span> perfectly fits the data, and
therefore serves as our reference point for goodness-of-fit. We now use the
log-likelihood values of these models to calculate the deviance. For the
residual deviance <span class="math inline">\(D_p\)</span>, we have:</p>
<p><span class="math display">\[
\begin{aligned}
D_p &amp;= 2 \times (LL_s - LL_p) \\
&amp;= 2 \times (0 - (-13.18263)) \\
&amp;= 2 \times 13.18263 \\
&amp;= 26.36526
\end{aligned}
\]</span></p>
<p>and for the null deviance <span class="math inline">\(D_0\)</span>, we have:</p>
<p><span class="math display">\[
\begin{aligned}
D_0 &amp;= 2 \times (LL_s - LL_0) \\
&amp;= 2 \times (0 - (-13.46023)) \\
&amp;= 2 \times 13.46023 \\
&amp;= 26.92047
\end{aligned}
\]</span></p>
<p>As we can see, the deviance is two times the difference between the
log-likelihood of the saturated model and the log-likelihood of the proposed
model for the residual deviance or the log-likelihood of the null model for the
null deviance. The deviance quantifies how much the null and proposed models
differ from the saturated model in terms of goodness-of-fit.</p>
<p>In a following chapter, we will explain how we can use these deviance value to
perform statistical hypothesis tests to formally compare the proposed model to
the null model.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="missingness.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/02-deviance.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
